name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: deploy_automated
  REGION: us-central1
  SERVICE_NAME: ai-driven-deployment
  IMAGE_NAME: cloud-application
  REPO_NAME: gen-ai-poc/ai-poc

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout-code-v1

    - name: Authenticate to Google Cloud
      uses: google-github-actions/setup-auth-v1
      with:
        credentials_json: '${{secrets.AWS_SA_KEY}}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-aws-v1
      with:
        project_id: ${{env.PROJECT_ID}}

    - name: Configure Docker for Artifact Registry
      run: |
        google auth configure-docker ${{env.REGION}}-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build -t ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPO_NAME}}/${{env.IMAGE_NAME}}:$GITHUB_SHA .

    - name: Push Docker image to Artifact Registry
      run: |
        docker push ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPO_NAME}}/${{env.IMAGE_NAME}}:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        google run deploy ${{env.SERVICE_NAME}} \
          --image ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPO_NAME}}/${{env.IMAGE_NAME}}:$GITHUB_SHA \
          --region ${{env.REGION}} \
          --platform managed \
          --no-allow-unauthenticated

